//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.14 at 08:21:02 PM EDT 
//


package zswi.schemas.dav.allprop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{http://me.com/_namespace/}simple"/>
 *         &lt;element ref="{http://me.com/_namespace/}crud"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "simple",
    "crud"
})
@XmlRootElement(name = "bulk-requests", namespace = "http://me.com/_namespace/")
public class BulkRequests {

    @XmlElement(namespace = "http://me.com/_namespace/")
    protected Simple simple;
    @XmlElement(namespace = "http://me.com/_namespace/")
    protected Crud crud;

    /**
     * Gets the value of the simple property.
     * 
     * @return
     *     possible object is
     *     {@link Simple }
     *     
     */
    public Simple getSimple() {
        return simple;
    }

    /**
     * Sets the value of the simple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Simple }
     *     
     */
    public void setSimple(Simple value) {
        this.simple = value;
    }

    /**
     * Gets the value of the crud property.
     * 
     * @return
     *     possible object is
     *     {@link Crud }
     *     
     */
    public Crud getCrud() {
        return crud;
    }

    /**
     * Sets the value of the crud property.
     * 
     * @param value
     *     allowed object is
     *     {@link Crud }
     *     
     */
    public void setCrud(Crud value) {
        this.crud = value;
    }

}
