//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.13 at 08:24:41 PM EDT 
//


package zswi.schemas.dav.allprop;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zswi.schemas.dav.allprop package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Getcontenttype_QNAME = new QName("DAV:", "getcontenttype");
    private final static QName _CalendarOrder_QNAME = new QName("http://apple.com/ns/ical/", "calendar-order");
    private final static QName _ResourceClass_QNAME = new QName("http://twistedmatrix.com/xml_namespace/dav/", "resource-class");
    private final static QName _Getlastmodified_QNAME = new QName("DAV:", "getlastmodified");
    private final static QName _Href_QNAME = new QName("DAV:", "href");
    private final static QName _Displayname_QNAME = new QName("DAV:", "displayname");
    private final static QName _Getetag_QNAME = new QName("DAV:", "getetag");
    private final static QName _CalendarColor_QNAME = new QName("http://apple.com/ns/ical/", "calendar-color");
    private final static QName _CurrentUserPrincipal_QNAME = new QName("DAV:", "current-user-principal");
    private final static QName _Status_QNAME = new QName("DAV:", "status");
    private final static QName _Getctag_QNAME = new QName("http://calendarserver.org/ns/", "getctag");
    private final static QName _DefaultAlarmVeventDatetime_QNAME = new QName("urn:ietf:params:xml:ns:caldav", "default-alarm-vevent-datetime");
    private final static QName _ScheduleDefaultCalendarURL_QNAME = new QName("urn:ietf:params:xml:ns:caldav", "schedule-default-calendar-URL");
    private final static QName _ScheduleDefaultTasksURL_QNAME = new QName("http://calendarserver.org/ns/", "schedule-default-tasks-URL");
    private final static QName _Creationdate_QNAME = new QName("DAV:", "creationdate");
    private final static QName _DefaultAlarmVeventDate_QNAME = new QName("urn:ietf:params:xml:ns:caldav", "default-alarm-vevent-date");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zswi.schemas.dav.allprop
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Shared }
     * 
     */
    public Shared createShared() {
        return new Shared();
    }

    /**
     * Create an instance of {@link Supportedlock }
     * 
     */
    public Supportedlock createSupportedlock() {
        return new Supportedlock();
    }

    /**
     * Create an instance of {@link Lockentry }
     * 
     */
    public Lockentry createLockentry() {
        return new Lockentry();
    }

    /**
     * Create an instance of {@link Lockscope }
     * 
     */
    public Lockscope createLockscope() {
        return new Lockscope();
    }

    /**
     * Create an instance of {@link Exclusive }
     * 
     */
    public Exclusive createExclusive() {
        return new Exclusive();
    }

    /**
     * Create an instance of {@link Locktype }
     * 
     */
    public Locktype createLocktype() {
        return new Locktype();
    }

    /**
     * Create an instance of {@link Write }
     * 
     */
    public Write createWrite() {
        return new Write();
    }

    /**
     * Create an instance of {@link Href }
     * 
     */
    public Href createHref() {
        return new Href();
    }

    /**
     * Create an instance of {@link Multistatus }
     * 
     */
    public Multistatus createMultistatus() {
        return new Multistatus();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Propstat }
     * 
     */
    public Propstat createPropstat() {
        return new Propstat();
    }

    /**
     * Create an instance of {@link Prop }
     * 
     */
    public Prop createProp() {
        return new Prop();
    }

    /**
     * Create an instance of {@link Invite }
     * 
     */
    public Invite createInvite() {
        return new Invite();
    }

    /**
     * Create an instance of {@link Getcontentlength }
     * 
     */
    public Getcontentlength createGetcontentlength() {
        return new Getcontentlength();
    }

    /**
     * Create an instance of {@link Resourcetype }
     * 
     */
    public Resourcetype createResourcetype() {
        return new Resourcetype();
    }

    /**
     * Create an instance of {@link Collection }
     * 
     */
    public Collection createCollection() {
        return new Collection();
    }

    /**
     * Create an instance of {@link DropboxHome }
     * 
     */
    public DropboxHome createDropboxHome() {
        return new DropboxHome();
    }

    /**
     * Create an instance of {@link FreeBusyUrl }
     * 
     */
    public FreeBusyUrl createFreeBusyUrl() {
        return new FreeBusyUrl();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link Calendar }
     * 
     */
    public Calendar createCalendar() {
        return new Calendar();
    }

    /**
     * Create an instance of {@link ScheduleInbox }
     * 
     */
    public ScheduleInbox createScheduleInbox() {
        return new ScheduleInbox();
    }

    /**
     * Create an instance of {@link ScheduleOutbox }
     * 
     */
    public ScheduleOutbox createScheduleOutbox() {
        return new ScheduleOutbox();
    }

    /**
     * Create an instance of {@link ScheduleCalendarTransp }
     * 
     */
    public ScheduleCalendarTransp createScheduleCalendarTransp() {
        return new ScheduleCalendarTransp();
    }

    /**
     * Create an instance of {@link Opaque }
     * 
     */
    public Opaque createOpaque() {
        return new Opaque();
    }

    /**
     * Create an instance of {@link Transparent }
     * 
     */
    public Transparent createTransparent() {
        return new Transparent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "DAV:", name = "getcontenttype")
    public JAXBElement<String> createGetcontenttype(String value) {
        return new JAXBElement<String>(_Getcontenttype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://apple.com/ns/ical/", name = "calendar-order")
    public JAXBElement<BigInteger> createCalendarOrder(BigInteger value) {
        return new JAXBElement<BigInteger>(_CalendarOrder_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://twistedmatrix.com/xml_namespace/dav/", name = "resource-class")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createResourceClass(String value) {
        return new JAXBElement<String>(_ResourceClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "DAV:", name = "getlastmodified")
    public JAXBElement<String> createGetlastmodified(String value) {
        return new JAXBElement<String>(_Getlastmodified_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "DAV:", name = "href")
    public JAXBElement<String> createHref(String value) {
        return new JAXBElement<String>(_Href_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "DAV:", name = "displayname")
    public JAXBElement<String> createDisplayname(String value) {
        return new JAXBElement<String>(_Displayname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "DAV:", name = "getetag")
    public JAXBElement<String> createGetetag(String value) {
        return new JAXBElement<String>(_Getetag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://apple.com/ns/ical/", name = "calendar-color")
    public JAXBElement<String> createCalendarColor(String value) {
        return new JAXBElement<String>(_CalendarColor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Href }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "DAV:", name = "current-user-principal")
    public JAXBElement<Href> createCurrentUserPrincipal(Href value) {
        return new JAXBElement<Href>(_CurrentUserPrincipal_QNAME, Href.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "DAV:", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://calendarserver.org/ns/", name = "getctag")
    public JAXBElement<String> createGetctag(String value) {
        return new JAXBElement<String>(_Getctag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:caldav", name = "default-alarm-vevent-datetime")
    public JAXBElement<String> createDefaultAlarmVeventDatetime(String value) {
        return new JAXBElement<String>(_DefaultAlarmVeventDatetime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Href }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:caldav", name = "schedule-default-calendar-URL")
    public JAXBElement<Href> createScheduleDefaultCalendarURL(Href value) {
        return new JAXBElement<Href>(_ScheduleDefaultCalendarURL_QNAME, Href.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Href }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://calendarserver.org/ns/", name = "schedule-default-tasks-URL")
    public JAXBElement<Href> createScheduleDefaultTasksURL(Href value) {
        return new JAXBElement<Href>(_ScheduleDefaultTasksURL_QNAME, Href.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "DAV:", name = "creationdate")
    public JAXBElement<String> createCreationdate(String value) {
        return new JAXBElement<String>(_Creationdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:caldav", name = "default-alarm-vevent-date")
    public JAXBElement<String> createDefaultAlarmVeventDate(String value) {
        return new JAXBElement<String>(_DefaultAlarmVeventDate_QNAME, String.class, null, value);
    }

}
