//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.13 at 08:24:41 PM EDT 
//


package zswi.schemas.dav.allprop;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://calendarserver.org/ns/}invite" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:caldav}default-alarm-vevent-datetime" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:caldav}default-alarm-vevent-date" minOccurs="0"/>
 *         &lt;element ref="{DAV}creationdate" minOccurs="0"/>
 *         &lt;element ref="{DAV}current-user-principal" minOccurs="0"/>
 *         &lt;element ref="{DAV}displayname" minOccurs="0"/>
 *         &lt;element ref="{DAV}getcontentlength" minOccurs="0"/>
 *         &lt;element ref="{DAV}getcontenttype" minOccurs="0"/>
 *         &lt;element ref="{DAV}getetag" minOccurs="0"/>
 *         &lt;element ref="{DAV}getlastmodified" minOccurs="0"/>
 *         &lt;element ref="{DAV}resourcetype" minOccurs="0"/>
 *         &lt;element ref="{DAV}supportedlock" minOccurs="0"/>
 *         &lt;element ref="{http://apple.com/ns/ical/}calendar-color" minOccurs="0"/>
 *         &lt;element ref="{http://apple.com/ns/ical/}calendar-order" minOccurs="0"/>
 *         &lt;element ref="{http://calendarserver.org/ns/}getctag" minOccurs="0"/>
 *         &lt;element ref="{http://calendarserver.org/ns/}schedule-default-tasks-URL" minOccurs="0"/>
 *         &lt;element ref="{http://twistedmatrix.com/xml_namespace/dav/}resource-class" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:caldav}schedule-calendar-transp" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:caldav}schedule-default-calendar-URL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invite",
    "defaultAlarmVeventDatetime",
    "defaultAlarmVeventDate",
    "creationdate",
    "currentUserPrincipal",
    "displayname",
    "getcontentlength",
    "getcontenttype",
    "getetag",
    "getlastmodified",
    "resourcetype",
    "supportedlock",
    "calendarColor",
    "calendarOrder",
    "getctag",
    "scheduleDefaultTasksURL",
    "resourceClass",
    "scheduleCalendarTransp",
    "scheduleDefaultCalendarURL"
})
@XmlRootElement(name = "prop")
public class Prop {

    @XmlElement(namespace = "http://calendarserver.org/ns/")
    protected Invite invite;
    @XmlElement(name = "default-alarm-vevent-datetime", namespace = "urn:ietf:params:xml:ns:caldav")
    protected String defaultAlarmVeventDatetime;
    @XmlElement(name = "default-alarm-vevent-date", namespace = "urn:ietf:params:xml:ns:caldav")
    protected String defaultAlarmVeventDate;
    protected String creationdate;
    @XmlElement(name = "current-user-principal")
    protected Href currentUserPrincipal;
    protected String displayname;
    protected Getcontentlength getcontentlength;
    protected String getcontenttype;
    protected String getetag;
    protected String getlastmodified;
    protected Resourcetype resourcetype;
    protected Supportedlock supportedlock;
    @XmlElement(name = "calendar-color", namespace = "http://apple.com/ns/ical/")
    protected String calendarColor;
    @XmlElement(name = "calendar-order", namespace = "http://apple.com/ns/ical/")
    protected BigInteger calendarOrder;
    @XmlElement(namespace = "http://calendarserver.org/ns/")
    protected String getctag;
    @XmlElement(name = "schedule-default-tasks-URL", namespace = "http://calendarserver.org/ns/")
    protected Href scheduleDefaultTasksURL;
    @XmlElement(name = "resource-class", namespace = "http://twistedmatrix.com/xml_namespace/dav/")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String resourceClass;
    @XmlElement(name = "schedule-calendar-transp", namespace = "urn:ietf:params:xml:ns:caldav")
    protected ScheduleCalendarTransp scheduleCalendarTransp;
    @XmlElement(name = "schedule-default-calendar-URL", namespace = "urn:ietf:params:xml:ns:caldav")
    protected Href scheduleDefaultCalendarURL;

    /**
     * Gets the value of the invite property.
     * 
     * @return
     *     possible object is
     *     {@link Invite }
     *     
     */
    public Invite getInvite() {
        return invite;
    }

    /**
     * Sets the value of the invite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invite }
     *     
     */
    public void setInvite(Invite value) {
        this.invite = value;
    }

    /**
     * Gets the value of the defaultAlarmVeventDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultAlarmVeventDatetime() {
        return defaultAlarmVeventDatetime;
    }

    /**
     * Sets the value of the defaultAlarmVeventDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultAlarmVeventDatetime(String value) {
        this.defaultAlarmVeventDatetime = value;
    }

    /**
     * Gets the value of the defaultAlarmVeventDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultAlarmVeventDate() {
        return defaultAlarmVeventDate;
    }

    /**
     * Sets the value of the defaultAlarmVeventDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultAlarmVeventDate(String value) {
        this.defaultAlarmVeventDate = value;
    }

    /**
     * Gets the value of the creationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationdate() {
        return creationdate;
    }

    /**
     * Sets the value of the creationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationdate(String value) {
        this.creationdate = value;
    }

    /**
     * Gets the value of the currentUserPrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link Href }
     *     
     */
    public Href getCurrentUserPrincipal() {
        return currentUserPrincipal;
    }

    /**
     * Sets the value of the currentUserPrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Href }
     *     
     */
    public void setCurrentUserPrincipal(Href value) {
        this.currentUserPrincipal = value;
    }

    /**
     * Gets the value of the displayname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * Sets the value of the displayname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayname(String value) {
        this.displayname = value;
    }

    /**
     * Gets the value of the getcontentlength property.
     * 
     * @return
     *     possible object is
     *     {@link Getcontentlength }
     *     
     */
    public Getcontentlength getGetcontentlength() {
        return getcontentlength;
    }

    /**
     * Sets the value of the getcontentlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Getcontentlength }
     *     
     */
    public void setGetcontentlength(Getcontentlength value) {
        this.getcontentlength = value;
    }

    /**
     * Gets the value of the getcontenttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetcontenttype() {
        return getcontenttype;
    }

    /**
     * Sets the value of the getcontenttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetcontenttype(String value) {
        this.getcontenttype = value;
    }

    /**
     * Gets the value of the getetag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetetag() {
        return getetag;
    }

    /**
     * Sets the value of the getetag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetetag(String value) {
        this.getetag = value;
    }

    /**
     * Gets the value of the getlastmodified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetlastmodified() {
        return getlastmodified;
    }

    /**
     * Sets the value of the getlastmodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetlastmodified(String value) {
        this.getlastmodified = value;
    }

    /**
     * Gets the value of the resourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link Resourcetype }
     *     
     */
    public Resourcetype getResourcetype() {
        return resourcetype;
    }

    /**
     * Sets the value of the resourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resourcetype }
     *     
     */
    public void setResourcetype(Resourcetype value) {
        this.resourcetype = value;
    }

    /**
     * Gets the value of the supportedlock property.
     * 
     * @return
     *     possible object is
     *     {@link Supportedlock }
     *     
     */
    public Supportedlock getSupportedlock() {
        return supportedlock;
    }

    /**
     * Sets the value of the supportedlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Supportedlock }
     *     
     */
    public void setSupportedlock(Supportedlock value) {
        this.supportedlock = value;
    }

    /**
     * Gets the value of the calendarColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalendarColor() {
        return calendarColor;
    }

    /**
     * Sets the value of the calendarColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalendarColor(String value) {
        this.calendarColor = value;
    }

    /**
     * Gets the value of the calendarOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCalendarOrder() {
        return calendarOrder;
    }

    /**
     * Sets the value of the calendarOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCalendarOrder(BigInteger value) {
        this.calendarOrder = value;
    }

    /**
     * Gets the value of the getctag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetctag() {
        return getctag;
    }

    /**
     * Sets the value of the getctag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetctag(String value) {
        this.getctag = value;
    }

    /**
     * Gets the value of the scheduleDefaultTasksURL property.
     * 
     * @return
     *     possible object is
     *     {@link Href }
     *     
     */
    public Href getScheduleDefaultTasksURL() {
        return scheduleDefaultTasksURL;
    }

    /**
     * Sets the value of the scheduleDefaultTasksURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link Href }
     *     
     */
    public void setScheduleDefaultTasksURL(Href value) {
        this.scheduleDefaultTasksURL = value;
    }

    /**
     * Gets the value of the resourceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceClass() {
        return resourceClass;
    }

    /**
     * Sets the value of the resourceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceClass(String value) {
        this.resourceClass = value;
    }

    /**
     * Gets the value of the scheduleCalendarTransp property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleCalendarTransp }
     *     
     */
    public ScheduleCalendarTransp getScheduleCalendarTransp() {
        return scheduleCalendarTransp;
    }

    /**
     * Sets the value of the scheduleCalendarTransp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleCalendarTransp }
     *     
     */
    public void setScheduleCalendarTransp(ScheduleCalendarTransp value) {
        this.scheduleCalendarTransp = value;
    }

    /**
     * Gets the value of the scheduleDefaultCalendarURL property.
     * 
     * @return
     *     possible object is
     *     {@link Href }
     *     
     */
    public Href getScheduleDefaultCalendarURL() {
        return scheduleDefaultCalendarURL;
    }

    /**
     * Sets the value of the scheduleDefaultCalendarURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link Href }
     *     
     */
    public void setScheduleDefaultCalendarURL(Href value) {
        this.scheduleDefaultCalendarURL = value;
    }

}
