//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.13 at 08:24:41 PM EDT 
//


package zswi.schemas.dav.allprop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:ietf:params:xml:ns:caldav}opaque"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:caldav}transparent"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opaque",
    "transparent"
})
@XmlRootElement(name = "schedule-calendar-transp", namespace = "urn:ietf:params:xml:ns:caldav")
public class ScheduleCalendarTransp {

    @XmlElement(namespace = "urn:ietf:params:xml:ns:caldav")
    protected Opaque opaque;
    @XmlElement(namespace = "urn:ietf:params:xml:ns:caldav")
    protected Transparent transparent;

    /**
     * Gets the value of the opaque property.
     * 
     * @return
     *     possible object is
     *     {@link Opaque }
     *     
     */
    public Opaque getOpaque() {
        return opaque;
    }

    /**
     * Sets the value of the opaque property.
     * 
     * @param value
     *     allowed object is
     *     {@link Opaque }
     *     
     */
    public void setOpaque(Opaque value) {
        this.opaque = value;
    }

    /**
     * Gets the value of the transparent property.
     * 
     * @return
     *     possible object is
     *     {@link Transparent }
     *     
     */
    public Transparent getTransparent() {
        return transparent;
    }

    /**
     * Sets the value of the transparent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transparent }
     *     
     */
    public void setTransparent(Transparent value) {
        this.transparent = value;
    }

}
